---

- hosts: all
  strategy: debug
  gather_facts: true
  become: true
  tasks:

     - name: Include installation playbook of Flask and MySQL
       include: database.yml

  post_tasks:
     - name: Verify
       include: verify.yml

  roles:
     - geerlingguy.mysql
